name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << EOF
            cd /path/to/your/project
            git pull origin main
            # Add any other commands here, such as restarting services
            sudo systemctl restart your-service
          EOF
        
