name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    

      - name: Deploy to EC2 instance
        run: |
           
            cd /path/to/your/project
            git pull origin main
            
